server:
  port: 7001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demographic-data
    username: healthcare
    password: Healthcare123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7001